let () =
  match Array.to_list Sys.argv with
  | [_; "-i"; input; "-o"; output] ->
    let input = open_in input in
    let output = open_out output in
    output_string output "(* Generated by embed.ml *)\n";
    output_string output "let value =\n";
    begin try
        while true do
          let line = input_line input ^ "\n" in
          if String.length line < 2 || String.sub line 0 2 <> ";!" then
            output_string output ("  \"" ^ String.escaped line ^ "\" ^\n")
        done
      with
      | End_of_file -> output_string output "  \"\""
    end
  | _ ->
    prerr_endline "Usage: ocaml embed.ml -i <input> -o <output>"
