let () =
  output_string stdout "(* Generated by embed.ml *)\n";
  output_string stdout "let value =\n";
  try
    while true do
      let line = input_line stdin ^ "\n" in
      if String.length line < 2 || String.sub line 0 2 <> ";!" then
        output_string stdout ("  \"" ^ String.escaped line ^ "\" ^\n")
    done
  with
  | End_of_file -> output_string stdout "  \"\""
